version: "3"
networks:
  rabbit:
    driver: bridge
  auth:
    driver: bridge
  images:
    driver: bridge

services:
  telegram_bot_service_csysbot:
    build:
      context: ../
      dockerfile: ./build/DockerfileBot
    image: telegram_bot_service_csysbot_docker_image
    environment:
      USC_LOG_LEVEL: INFO
      USC_AMQP_URI: "amqp://guest:guest@rabbit:5672/"
      USC_TGBOT_TOKEN: ""
      USC_TGBOT_TIMEOUT: 60
      USC_AUTH_URI: "http://auth_service_csysbot:8099"
      USC_DEBUG_HOST: 0.0.0.0
      USC_DEBUG_PORT: 8011
    depends_on:
      rabbit:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8011:8011"
    expose:
      - 8011
    networks:
      - rabbit
      - auth

  cloud_storage_service_csysbot:
    build:
      context: ../
      dockerfile: ./build/DockerfileCloudStorage
    image: cloud_storage_service_csysbot_docker_image
    environment:
      USC_LOG_LEVEL: INFO
      USC_AMQP_URI: "amqp://guest:guest@rabbit:5672/"
      USC_AUTH_URI: "http://auth_service_csysbot:8099"
      USC_STORAGE_FOLDER: ""
      USC_DEBUG_TOKEN: ""
      USC_DEBUG_HOST: 0.0.0.0
      USC_DEBUG_PORT: 8022
    depends_on:
      rabbit:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8022:8022"
    expose:
      - 8022
    networks:
      - rabbit
      - auth
      - images

  auth_service_csysbot:
    build:
      context: ../
      dockerfile: ./build/DockerfileAuth
    image: auth_service_csysbot_docker_image
    environment:
      USC_LOG_LEVEL: INFO
      USC_HTTP_HOST: 0.0.0.0
      USC_HTTP_PORT_PUBLIC: 8033
      USC_HTTP_PORT_PRIVATE: 8099
      USC_YDISK_ID: ""
      USC_YDISK_SECRET: ""
    restart: on-failure
    ports:
      - "8033:8033"
      - "8099:8099"
    expose:
      - 8033
      - 8099
    networks:
      - auth
    depends_on:
      rabbit:
        condition: service_healthy
  
  rabbit:
    image: rabbitmq:3.9.25-management
    networks:
      - rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  server-images:
    build:
      context: ../
      dockerfile: ./build/DockerfileServerImages
    image: server_images_csysbot_docker_image  
    ports:
      - "8080:80"
    expose:
      - 80
    environment:      
      - NGINX_PORT=80
    networks:
      - images
