apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-service-deployment
  labels:
    app: pay-service
spec:
  selector:
    matchLabels:
      app: pay-service
  replicas: 1
  template:
    metadata:
      labels:
        app: pay-service
    spec:
      containers:
        - name: pay-service
          image: julinserg/pay_service_saga_docker_image:latest      
          env:
            - name: USC_LOG_LEVEL
              value: "INFO"        
            - name: USC_AMQP_URI
              value: "amqp://guest:guest@mq-shop-rabbitmq.default.svc.cluster.local:5672/"    
            - name: USC_PG_HOST
              value: "pg-pay-service-postgresql"
            - name: USC_PG_USER
              value: "postgres"
            - name: USC_PG_PASSWORD
              value: "postgres"
            - name: USC_PG_DB
              value: "shop_pay"
