apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bot-service-monitor
  labels:
    app: bot-service-monitor
spec:
  endpoints:
    - port: bot-metrics
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      scheme: http
  selector:
    matchLabels:
      app: bot-service
