apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-storage-service-monitor
  labels:
    app: cloud-storage-service-monitor
spec:
  endpoints:
    - port: cloud-storage-metrics
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      scheme: http
  selector:
    matchLabels:
      app: cloud-storage-service
