apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: metrics
      port: 8099
      targetPort: 8099
