apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: auth-public-metrics
      port: 8033
      targetPort: 8033
    - protocol: TCP
      name: auth-private-metrics
      port: 8099
      targetPort: 8099
